name: Lint Code

on: [push, pull_request]

jobs:
  build:
    name: Lint Code

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - run: npm install

    - run: npm run lint
      
    - run: npm run build:full

    - run: npm run changelog:generate:current

    - name: Display Tentative Changelog
      id: changelog
      run: |
        changelog="$(cat CHANGELOG-current.md)"
        changelog="${changelog//'%'/'%25'}"
        changelog="${changelog//$'\n'/'%0A'}"
        changelog="${changelog//$'\r'/'%0D'}"

        echo "$changelog"
        echo "::debug::Displaying Version/Changelog"
        echo "::debug::$(echo $GITHUB_REF | cut -d / -f 3)"
        echo "::debug::$changelog"