name: Fuck This Shit

on: [push]

jobs:
  build:
    name: For Real

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
  
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - run: npm install

    - uses: pCYSl5EDgo/cat@master
      id: test
      with:
        path: CHANGELOG.md

    - name: Display Tentative Changelog
      id: changelog
      env:
        TEXT: ${{ steps.test.outputs.text }}
      run: |
        echo "$TEXT"